name: Commit

on:
  push:
    branches:
      - '!master'
  pull_request:
    branches:
      - master

env:
  CI: true
  CARGO_TERM_COLOR: always

jobs:
  Setup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Protoc
        uses: arduino/setup-protoc@v3
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Build
        run: cargo build --all-features

      - name: Run tests
        run: cargo test --all-features

  CI:
    runs-on: ubuntu-latest
    needs:
      - Setup
    strategy:
      matrix:
        gateways: [
          { image: "rhiaqey/http", binary: "http" },
          { image: "rhiaqey/websocket", binary: "websocket" }
        ]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Build and push Docker image with Buildx (don't push on PR)
      # https://github.com/docker/build-push-action
      - name: Build docker image for ${{ matrix.gateways.binary }}
        uses: docker/build-push-action@c382f710d39a5bb4e430307530a720f50c2d3318
        with:
          context: .
          push: false
          tags: ${{ matrix.gateways.image }}:latest
          build-args: |
            BINARY=${{ matrix.gateways.binary }}
            FEATURES=${{ matrix.gateways.features }}
